### ISSUE TITLE
Upstream repo problem

### ISSUE THREAD

**Issue by DharminB** [HBRS-MAAS/ws18-project-right-brothers#16]
The upstream repo mentioned in the new homework is not possible to integrate with our team project repo. Our repos are not a fork of the upstream repo. In Last week's assignments as well, we had to copy and paste the `messages.md` file from one repo to another and then create a pull request.

Is there a way to solve this issue? @argenos

**Comment by argenos** [comment]
There is a good reason for keeping this two things separate, namely your pull requests should only contain the common code or the requested documentation; it is a bit harder, particularly for students without a lot of git experience, to make a pull request containing **only** those changes.
The second one comes from how the repositories are created in GitHub education, which creates independent repos instead of forks. 

For those reasons, at least for now, you need to maintain a fork of https://github.com/HBRS-MAAS/project and your own. 
In practice, however, the same principle as a fork applies. Locally you can add the `HBRS-MAAS/project` as an upstream remote, and 
* pull the changes from upstream 
* push your changes to your version of that fork
* make a pull request to the upstream change from said fork

cc @HBRS-MAAS/ws18
