### ISSUE TITLE
Orders in clients file

### ISSUE THREAD

**Issue by DharminB** [HBRS-MAAS/ws18-project-right-brothers#21]
@argenos Currently the orders are in the clients.json. Wouldn't it make sense to have all orders  in a seperate file (orders.json maybe)? They have a field called `customerId` anyway, which can be used to map an order to its corresponding customer.

**Comment by argenos** [comment]
This how it was done last year, however after you have loaded all orders from a single file, you still need to pass them to the right customer so they can make the order. This is particularly relevant if we are running different clients on different computers. 

I'm open to suggestions for the formatting of the config files, but I'd like to see a more concrete proposal of how the workflow would be before agreeing to the change. 

cc-ing @HBRS-MAAS/ws18 since this affects all teams

**Comment by DharminB** [comment]
I think you are correct. Linking can be avoided with the current design. 

I have another question related to this topic. The products mentioned inside `bakeries.json` have a complete description. I was wondering if other bakeries can have same product or not. If they can, would they have different `recipe` even with same product guid? If so, it would be better to just have guid of product in `bakeries.json` and have a seperate file for products. 

Another question was regarding the mismatch of info in `meta.json`. It says that there are 30 customers and 2 bakeries, whereas the corresponding files for these data contain only one of each.

**Comment by argenos** [comment]
> I have another question related to this topic. The products mentioned inside bakeries.json have a complete description. I was wondering if other bakeries can have same product or not. If they can, would they have different recipe even with same product guid? If so, it would be better to just have guid of product in bakeries.json and have a seperate file for products.
> 
Different bakeries can sell any type of bread and also have different recipes for the same product.
> Another question was regarding the mismatch of info in meta.json. It says that there are 30 customers and 2 bakeries, whereas the corresponding files for these data contain only one of each.
> 
It’s a mismatch since I haven’t updated the script to generate this files automatically. I had to split them manually due to time constraints, if only to give you an idea of what they look like. 

After next week when this has been updated, I’ll generate a couple of scenarios of different sizes, so you can test your projects more thoroughly. Keep in mind a lot of the things in there will be created randomly, e.g. the recipes don’t have all the actions listed in there, and the order will be randomized.
